import * as XLSX from 'xlsx';
import { InventoryItem, Customer, Supplier, Salesperson, PackagingVariant } from '../types';
import {
  getInventoryItems,
  saveInventoryItem,
  getCustomers,
  getSuppliers,
  getCurrentCompanyId,
  getCurrentBranchId,
} from '../db/roomDatabase';
import {
  importInventoryItems,
  importCustomersList,
  importSuppliersList,
  parsePackagingVariantsString,
  serializePackagingVariants,
} from './dataExportImportService';

export type MigrationEntityType = 'inventory' | 'customers' | 'suppliers';

export type MigrationJobStatus = 'draft' | 'in_review' | 'ready' | 'committed';

export type DuplicateConflictPolicy = 'skip' | 'update' | 'append_new';

export interface FieldDefinition {
  key: string;
  label: string;
  required?: boolean;
  type: 'string' | 'number' | 'boolean';
  synonyms: string[];
  description: string;
  defaultValue?: any;
}

export interface ColumnMapping {
  targetFieldKey: string;
  sourceHeader: string | null; // null if unmapped or auto-generated
  isAutoGenerated?: boolean;
  autoGenPrefix?: string;
}

export interface FormulaConfig {
  autoGenerateSku: boolean;
  skuPrefix: string;
  skuDigits: number;
  caseFormula: 'none' | 'case_cost_from_unit' | 'unit_cost_from_case';
  defaultCaseQuantity: number;
  markupFormula: 'none' | 'cost_plus_markup';
  markupPercent: number;
  taxAdjustment: 'none' | 'add_vat';
  taxPercent: number;
  cleanText: boolean; // trim whitespace and title case
  variantImportMode?: 'parse_column' | 'auto_generate' | 'none';
  autoVariantPreset?: 'none' | 'half_pack' | 'double_pack' | 'five_pack' | 'ten_pack';
  autoVariantDiscountPercent?: number;
}

export interface BatchPartition {
  id: string;
  batchNumber: number;
  title: string;
  assignedStaffId?: string;
  assignedStaffName?: string;
  startIndex: number;
  endIndex: number; // inclusive
  totalRows: number;
  status: 'pending' | 'in_progress' | 'verified';
  notes?: string;
}

export interface StagedRow {
  _rowId: string;
  _isValid: boolean;
  _validationErrors: string[];
  _isDuplicate?: boolean;
  [key: string]: any;
}

export interface MigrationJob {
  id: string;
  title: string;
  entityType: MigrationEntityType;
  createdAt: string;
  updatedAt: string;
  status: MigrationJobStatus;
  fileName?: string;
  rawHeaders: string[];
  mappings: Record<string, ColumnMapping>;
  formulas: FormulaConfig;
  partitions: BatchPartition[];
  stagedRows: StagedRow[];
  totalRows: number;
  verifiedRows: number;
  conflictPolicy: DuplicateConflictPolicy;
  committedAt?: string;
  rollbackSnapshotKey?: string;
}

export const STORAGE_MIGRATION_JOBS_KEY = 'saimetric_migration_jobs';
export const STORAGE_MIGRATION_PRESETS_KEY = 'saimetric_migration_presets';

// =========================================================================
// FIELD DEFINITIONS WITH RICH SYNONYMS
// =========================================================================

export const INVENTORY_FIELDS: FieldDefinition[] = [
  {
    key: 'itemId',
    label: 'Item ID / Product Code',
    type: 'string',
    synonyms: [
      'item_id',
      'itemid',
      'id',
      'product_id',
      'productid',
      'item_code',
      'itemcode',
    ],
    description: 'Unique internal inventory item identifier (e.g. MAZ001, SUG001).',
  },
  {
    key: 'name',
    label: 'Product / Item Name',
    required: true,
    type: 'string',
    synonyms: [
      'item_name',
      'itemname',
      'product_name',
      'productname',
      'product',
      'title',
      'product_description',
      'item_description',
      'desc',
      'description',
      'details',
    ],
    description: 'Name of the item as displayed on POS and customer receipt.',
  },
  {
    key: 'sku',
    label: 'SKU / Stock Code',
    type: 'string',
    synonyms: [
      'sku',
      'stock_code',
      'stockcode',
      'part_number',
      'ref',
      'reference',
      'stock_keeping_unit',
    ],
    description: 'Unique internal inventory item code or SKU. Auto-generated if missing.',
  },
  {
    key: 'barcode',
    label: 'Barcode / UPC',
    type: 'string',
    synonyms: [
      'barcode',
      'bar_code',
      'upc',
      'ean',
      'ean13',
      'scan_code',
      'scancode',
      'plu',
      'barcodeno',
      'bar_code_no',
    ],
    description: 'Scannable manufacturer barcode.',
  },
  {
    key: 'category',
    label: 'Category / Department',
    type: 'string',
    synonyms: [
      'category',
      'department',
      'dept',
      'group',
      'item_group',
      'product_group',
      'cat',
      'family',
      'classification',
    ],
    description: 'Product department (e.g. Groceries, Beverages, Hardware).',
    defaultValue: 'General',
  },
  {
    key: 'costPrice',
    label: 'Cost Price / Unit Cost ($)',
    required: true,
    type: 'number',
    synonyms: [
      'cost_per_unit',
      'cost_per_unit_$',
      'costperunit',
      'unit_cost',
      'unitcost',
      'cost',
      'cost_price',
      'buying_price',
      'purchase_price',
      'buy_price',
      'last_cost',
      'costprice',
      'buyprice',
      'buying',
      'supplier_cost',
    ],
    description: 'Wholesale acquisition cost per unit.',
    defaultValue: 0,
  },
  {
    key: 'sellingPrice',
    label: 'Selling Price / Unit Price ($)',
    required: true,
    type: 'number',
    synonyms: [
      'sell_price_unit',
      'sell_price_unit_$',
      'sellpriceunit',
      'unit_price',
      'unitprice',
      'price',
      'selling_price',
      'retail',
      'retail_price',
      'sales_price',
      'sale_price',
      'selling',
      'sellingprice',
      'retailprice',
      'price_inc_vat',
    ],
    description: 'Standard retail selling price per single unit.',
    defaultValue: 0,
  },
  {
    key: 'stockCases',
    label: 'Stock Cases (Unopened)',
    type: 'number',
    synonyms: [
      'stock_cases',
      'stockcases',
      'cases_in_stock',
      'cases_on_hand',
      'cases_count',
      'cases',
    ],
    description: 'Whole unopened cartons or cases in stock.',
    defaultValue: 0,
  },
  {
    key: 'stockSingles',
    label: 'Stock Singles (Loose Units)',
    type: 'number',
    synonyms: [
      'stock_singles',
      'stocksingles',
      'singles',
      'loose_units',
      'singles_in_stock',
      'qtysingles',
      'loose_stock',
    ],
    description: 'Individual loose or opened units in stock.',
    defaultValue: 0,
  },
  {
    key: 'stockQuantity',
    label: 'Stock on Hand / Total Units',
    type: 'number',
    synonyms: [
      'total_units',
      'totalunits',
      'qty',
      'quantity',
      'stock',
      'stock_on_hand',
      'soh',
      'current_stock',
      'balance',
      'units',
      'count',
      'qty_on_hand',
      'available_stock',
    ],
    description: 'Initial stock on hand in total single units.',
    defaultValue: 0,
  },
  {
    key: 'caseQuantity',
    label: 'Units Per Case / Pack',
    type: 'number',
    synonyms: [
      'units_per_case',
      'unitspercase',
      'case_qty',
      'case_quantity',
      'pack_size',
      'case_size',
      'pack_qty',
      'outer_pack',
      'ctn_qty',
      'carton_qty',
    ],
    description: 'How many units are in one wholesale carton/case (e.g. 24).',
    defaultValue: 1,
  },
  {
    key: 'caseCost',
    label: 'Case / Carton Cost ($)',
    type: 'number',
    synonyms: [
      'cost_per_case',
      'cost_per_case_$',
      'costpercase',
      'case_cost',
      'carton_cost',
      'case_price',
      'pack_cost',
      'outer_cost',
      'ctn_cost',
      'casecost',
    ],
    description: 'Cost for an entire wholesale case. Can be derived automatically.',
    defaultValue: 0,
  },
  {
    key: 'casePrice',
    label: 'Case Selling Price ($)',
    type: 'number',
    synonyms: [
      'sell_price_case',
      'sell_price_case_$',
      'sellpricecase',
      'case_price',
      'case_selling_price',
      'case_sell_price',
    ],
    description: 'Selling price for a full wholesale carton/case.',
    defaultValue: 0,
  },
  {
    key: 'packagingVariants',
    label: 'Packaging Variants / Prepacks',
    type: 'string',
    synonyms: [
      'packaging_variants_prepacks',
      'packaging_variants',
      'packagingvariants',
      'packaging_variant',
      'variants',
      'variant',
      'prepacks',
      'prepack',
      'sub_packs',
      'pack_sizes',
      'custom_packs',
    ],
    description: 'Prepacks or pack breakdown variants (e.g. "Prepack (5s): units=5, price=1.00").',
  },
  {
    key: 'parentId',
    label: 'Parent Product SKU / ID (For Prepacks/Variants)',
    type: 'string',
    synonyms: [
      'parent_id',
      'parent_sku',
      'parent_item_id',
      'parent_product',
      'parent_product_sku_id',
      'parent_product_sku',
      'parent_code',
      'parentid',
      'parentsku',
      'parent',
    ],
    description: 'Link this prepack/variant directly to a parent product. Converts variant stock into parent units automatically without manual case breaking.',
  },
  {
    key: 'variantUnits',
    label: 'Units in Prepack / Variant',
    type: 'number',
    synonyms: [
      'units_in_variant',
      'variant_units',
      'units_in_pack',
      'units_per_pack',
      'pack_units',
      'units_in_prepack',
      'prepack_units',
      'pieces_in_pack',
    ],
    description: 'Number of base units contained in this prepack (e.g. 4 for prepack of 4 lollipops, 6 for 6 eggs).',
    defaultValue: 1,
  },
  {
    key: 'canSellAsCase',
    label: 'Can Sell As Case (Y/N)',
    type: 'string',
    synonyms: [
      'can_sell_as_case_y_n',
      'can_sell_as_case',
      'cansellascase',
      'sell_as_case',
      'sellcase',
    ],
    description: 'Whether full cases can be sold directly on the register (Y/N).',
    defaultValue: 'N',
  },
  {
    key: 'unit',
    label: 'Unit of Measure',
    type: 'string',
    synonyms: [
      'unit',
      'uom',
      'measure',
      'unit_of_measure',
      'packaging',
      'pack_type',
    ],
    description: 'e.g. Units, kg, Litres, Bags, Bottles.',
    defaultValue: 'Units',
  },
  {
    key: 'supplierName',
    label: 'Primary Supplier / Vendor',
    type: 'string',
    synonyms: [
      'supplier',
      'supplier_name',
      'vendor',
      'vendor_name',
      'source',
      'wholesaler',
    ],
    description: 'Primary supplier name.',
  },
  {
    key: 'minStock',
    label: 'Min Stock Level (Reorder Units)',
    type: 'number',
    synonyms: [
      'reorder_level_units',
      'reorderlevelunits',
      'min_stock',
      'minimum_stock',
      'reorder_level',
      'reorder_point',
      'low_stock_alert',
      'safety_stock',
    ],
    description: 'Threshold single units when low stock alert triggers.',
    defaultValue: 5,
  },
  {
    key: 'reorderLevelCases',
    label: 'Reorder Level Cases',
    type: 'number',
    synonyms: [
      'reorder_level_cases',
      'reorderlevelcases',
      'min_cases',
    ],
    description: 'Threshold cases when case reorder alert triggers.',
    defaultValue: 1,
  },
  {
    key: 'description',
    label: 'Item Description / Notes',
    type: 'string',
    synonyms: [
      'description',
      'desc',
      'notes',
      'details',
      'product_notes',
    ],
    description: 'Detailed description or specifications of the item.',
  },
];

export const CUSTOMER_FIELDS: FieldDefinition[] = [
  {
    key: 'name',
    label: 'Customer / Business Name',
    required: true,
    type: 'string',
    synonyms: [
      'customer',
      'customer_name',
      'name',
      'client',
      'client_name',
      'company',
      'account_name',
      'debtor_name',
    ],
    description: 'Full name or company name of customer.',
  },
  {
    key: 'phone',
    label: 'Phone / Cell Number',
    required: true,
    type: 'string',
    synonyms: [
      'phone',
      'cell',
      'cellphone',
      'mobile',
      'telephone',
      'contact_number',
      'contact',
      'whatsapp',
      'phone_number',
      'cell_no',
    ],
    description: 'Primary mobile number for SMS/receipts/debt tracking.',
  },
  {
    key: 'email',
    label: 'Email Address',
    type: 'string',
    synonyms: ['email', 'email_address', 'mail', 'e_mail'],
    description: 'Customer contact email.',
  },
  {
    key: 'address',
    label: 'Physical / Store Address',
    type: 'string',
    synonyms: [
      'address',
      'physical_address',
      'location',
      'street',
      'city',
      'store_location',
    ],
    description: 'Delivery or physical shop address.',
  },
  {
    key: 'creditLimit',
    label: 'Credit Limit',
    type: 'number',
    synonyms: [
      'credit_limit',
      'limit',
      'max_credit',
      'allowed_credit',
      'credit_ceiling',
    ],
    description: 'Maximum credit ceiling allowed.',
    defaultValue: 500,
  },
  {
    key: 'currentBalance',
    label: 'Opening Debt / Balance',
    type: 'number',
    synonyms: [
      'balance',
      'current_balance',
      'opening_balance',
      'debt',
      'amount_due',
      'balance_due',
      'outstanding',
      'dr_balance',
    ],
    description: 'Existing debt brought forward from previous system.',
    defaultValue: 0,
  },
  {
    key: 'notes',
    label: 'Account Notes',
    type: 'string',
    synonyms: ['notes', 'remarks', 'comments', 'memo'],
    description: 'Special customer terms or relationship notes.',
  },
];

export const SUPPLIER_FIELDS: FieldDefinition[] = [
  {
    key: 'name',
    label: 'Supplier / Vendor Name',
    required: true,
    type: 'string',
    synonyms: [
      'supplier',
      'supplier_name',
      'vendor',
      'vendor_name',
      'name',
      'company_name',
      'creditor_name',
    ],
    description: 'Wholesale supplier name.',
  },
  {
    key: 'contactPerson',
    label: 'Contact Person / Representative',
    type: 'string',
    synonyms: ['contact_person', 'rep', 'sales_rep', 'agent', 'contact_name', 'contact'],
    description: 'Supplier sales representative or manager.',
  },
  {
    key: 'phone',
    label: 'Phone / Cell Number',
    type: 'string',
    synonyms: [
      'phone',
      'telephone',
      'cell',
      'mobile',
      'tel',
      'phone_no',
      'contact_phone',
    ],
    description: 'Supplier telephone/mobile.',
  },
  {
    key: 'email',
    label: 'Email Address',
    type: 'string',
    synonyms: ['email', 'email_address', 'mail'],
    description: 'Order placement email.',
  },
  {
    key: 'paymentTerms',
    label: 'Payment Terms (e.g. COD, 30 Days)',
    type: 'string',
    synonyms: ['payment_terms', 'terms', 'credit_terms', 'terms_of_payment'],
    description: 'COD, 7 Days, 14 Days, 30 Days, etc.',
    defaultValue: 'COD',
  },
  {
    key: 'address',
    label: 'Warehouse / Factory Address',
    type: 'string',
    synonyms: ['address', 'physical_address', 'factory_address', 'location'],
    description: 'Pickup or physical depot address.',
  },
];

/**
 * Get field definitions for an entity type
 */
export function getFieldDefinitionsForEntity(type: MigrationEntityType): FieldDefinition[] {
  switch (type) {
    case 'inventory':
      return INVENTORY_FIELDS;
    case 'customers':
      return CUSTOMER_FIELDS;
    case 'suppliers':
      return SUPPLIER_FIELDS;
  }
}

// =========================================================================
// SMART SYNONYM & HEADING AUTO-MATCHER
// =========================================================================

/**
 * Clean a string for synonym comparison
 */
function normalizeHeaderString(str: string): string {
  return str
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
}

const SYSTEM_INVENTORY_HEADER_MAP: Record<string, string> = {
  item_id: 'itemId',
  itemid: 'itemId',
  product_id: 'itemId',
  item_name: 'name',
  itemname: 'name',
  product_name: 'name',
  category: 'category',
  can_sell_as_case: 'canSellAsCase',
  can_sell_as_case_y_n: 'canSellAsCase',
  units_per_case: 'caseQuantity',
  cost_per_case: 'caseCost',
  cost_per_case_$: 'caseCost',
  cost_per_unit: 'costPrice',
  cost_per_unit_$: 'costPrice',
  sell_price_case: 'casePrice',
  sell_price_case_$: 'casePrice',
  sell_price_unit: 'sellingPrice',
  sell_price_unit_$: 'sellingPrice',
  stock_cases: 'stockCases',
  stock_singles: 'stockSingles',
  total_units: 'stockQuantity',
  reorder_level_cases: 'reorderLevelCases',
  reorder_level_units: 'minStock',
  sku: 'sku',
  barcode: 'barcode',
  description: 'description',
  packaging_variants: 'packagingVariants',
  packaging_variants_prepacks: 'packagingVariants',
  prepacks: 'packagingVariants',
  variants: 'packagingVariants',
  parent_id: 'parentId',
  parent_sku: 'parentId',
  parent_product: 'parentId',
  parent_product_sku_id: 'parentId',
  parent: 'parentId',
  units_in_variant: 'variantUnits',
  variant_units: 'variantUnits',
  units_per_pack: 'variantUnits',
};

const SYSTEM_CUSTOMER_HEADER_MAP: Record<string, string> = {
  customer_id: 'id',
  customer_name: 'name',
  phone_number: 'phone',
  phone: 'phone',
  physical_address: 'address',
  address: 'address',
  credit_limit: 'creditLimit',
  credit_allowed: 'creditAllowed',
  max_unpaid_receipts: 'maxReceipts',
  notes: 'notes',
};

const SYSTEM_SUPPLIER_HEADER_MAP: Record<string, string> = {
  supplier_id: 'id',
  supplier_name: 'name',
  contact_person: 'contactPerson',
  phone_number: 'phone',
  phone: 'phone',
  email_address: 'email',
  email: 'email',
  physical_address: 'address',
  address: 'address',
  bank_name: 'bankName',
  bank_account_number: 'bankAccount',
  tax_number: 'taxNumber',
  payment_terms_days: 'paymentTerms',
};

/**
 * Automatically map raw spreadsheet headers to Saimetric fields using fuzzy synonym dictionary
 */
export function autoMatchHeaders(
  entityType: MigrationEntityType,
  rawHeaders: string[]
): Record<string, ColumnMapping> {
  const fields = getFieldDefinitionsForEntity(entityType);
  const mappings: Record<string, ColumnMapping> = {};
  const usedRawHeaders = new Set<string>();
  const matchedFieldMap: Record<string, string> = {};

  const systemMap =
    entityType === 'inventory'
      ? SYSTEM_INVENTORY_HEADER_MAP
      : entityType === 'customers'
      ? SYSTEM_CUSTOMER_HEADER_MAP
      : SYSTEM_SUPPLIER_HEADER_MAP;

  // Pass 1: Saimetric System Known Exact Header Matching (100% guarantee for system exported files)
  for (const raw of rawHeaders) {
    const cleanRaw = normalizeHeaderString(raw);
    const targetKey = systemMap[cleanRaw];
    if (targetKey && !matchedFieldMap[targetKey] && fields.some((f) => f.key === targetKey)) {
      matchedFieldMap[targetKey] = raw;
      usedRawHeaders.add(raw);
    }
  }

  // Pass 2: Exact Match on field.key, field.label, or exact synonym
  for (const field of fields) {
    if (matchedFieldMap[field.key]) continue;
    const normKey = normalizeHeaderString(field.key);
    const normLabel = normalizeHeaderString(field.label);
    const normSynonyms = field.synonyms.map(normalizeHeaderString);

    for (const raw of rawHeaders) {
      if (usedRawHeaders.has(raw)) continue;
      const cleanRaw = normalizeHeaderString(raw);

      if (cleanRaw === normKey || cleanRaw === normLabel || normSynonyms.includes(cleanRaw)) {
        matchedFieldMap[field.key] = raw;
        usedRawHeaders.add(raw);
        break;
      }
    }
  }

  // Pass 3: Bounded partial matching (only for longer words, strictly avoiding generic collisions like 'item')
  for (const field of fields) {
    if (matchedFieldMap[field.key]) continue;
    const normSynonyms = field.synonyms.map(normalizeHeaderString).filter((s) => s.length >= 4);

    for (const raw of rawHeaders) {
      if (usedRawHeaders.has(raw)) continue;
      const cleanRaw = normalizeHeaderString(raw);

      const partialMatch = normSynonyms.find((s) => {
        if (cleanRaw.includes(s) || (s.includes(cleanRaw) && cleanRaw.length >= 4)) {
          return true;
        }
        return false;
      });

      if (partialMatch) {
        matchedFieldMap[field.key] = raw;
        usedRawHeaders.add(raw);
        break;
      }
    }
  }

  // Build final mappings
  for (const field of fields) {
    mappings[field.key] = {
      targetFieldKey: field.key,
      sourceHeader: matchedFieldMap[field.key] || null,
      isAutoGenerated: false,
    };
  }

  return mappings;
}

// =========================================================================
// FILE PARSING & INGESTION (EXCEL, CSV, TSV, JSON)
// =========================================================================

export interface ParsedFileResult {
  headers: string[];
  rows: Record<string, any>[];
  totalCount: number;
}

/**
 * Parse any uploaded file (Excel .xlsx, .xls, CSV, TSV, or JSON)
 */
export async function parseLegacyFile(file: File): Promise<ParsedFileResult> {
  const fileName = file.name.toLowerCase();

  if (fileName.endsWith('.json')) {
    const text = await file.text();
    const parsed = JSON.parse(text);
    const dataRows = Array.isArray(parsed) ? parsed : parsed.items || parsed.data || [];
    if (!dataRows.length) {
      throw new Error('JSON file contains no data rows.');
    }
    const headers = Object.keys(dataRows[0]);
    return {
      headers,
      rows: dataRows,
      totalCount: dataRows.length,
    };
  }

  // Handle Excel and CSV via XLSX parser
  const buffer = await file.arrayBuffer();
  const workbook = XLSX.read(buffer, { type: 'array' });
  const firstSheetName = workbook.SheetNames[0];
  if (!firstSheetName) {
    throw new Error('Uploaded spreadsheet has no worksheets.');
  }

  const sheet = workbook.Sheets[firstSheetName];
  // Parse as raw 2D array of rows
  const rawData: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: '' });
  if (rawData.length < 2) {
    throw new Error('Spreadsheet must contain at least a header row and 1 data row.');
  }

  // Extract headers
  const headerRow = rawData[0];
  const headers = headerRow.map((h: any, idx: number) => {
    const str = String(h ?? '').trim();
    return str || `Column_${idx + 1}`;
  });

  // Extract rows
  const rows: Record<string, any>[] = [];
  for (let r = 1; r < rawData.length; r++) {
    const rowValues = rawData[r];
    // Check if entire row is empty
    const hasData = rowValues.some((v: any) => v !== '' && v !== null && v !== undefined);
    if (!hasData) continue;

    const rowObj: Record<string, any> = {};
    headers.forEach((h: string, idx: number) => {
      rowObj[h] = rowValues[idx] !== undefined ? rowValues[idx] : '';
    });
    rows.push(rowObj);
  }

  return {
    headers,
    rows,
    totalCount: rows.length,
  };
}

/**
 * Parse pasted table text (from Excel clipboard or TSV)
 */
export function parsePastedTableText(text: string): ParsedFileResult {
  const lines = text.split(/\r?\n/).filter((l) => l.trim().length > 0);
  if (lines.length < 2) {
    throw new Error('Pasted text must contain at least a header line and 1 data line.');
  }

  // Detect delimiter: tab or comma
  const firstLine = lines[0];
  const delimiter = firstLine.includes('\t') ? '\t' : ',';

  const headers = firstLine.split(delimiter).map((h, idx) => h.trim().replace(/^"|"$/g, '') || `Column_${idx + 1}`);

  const rows: Record<string, any>[] = [];
  for (let i = 1; i < lines.length; i++) {
    const parts = lines[i].split(delimiter).map((v) => v.trim().replace(/^"|"$/g, ''));
    if (parts.length === 0 || parts.every((p) => p === '')) continue;

    const rowObj: Record<string, any> = {};
    headers.forEach((h, idx) => {
      rowObj[h] = parts[idx] !== undefined ? parts[idx] : '';
    });
    rows.push(rowObj);
  }

  return {
    headers,
    rows,
    totalCount: rows.length,
  };
}

// =========================================================================
// TRANSFORMATION & FORMULA ENGINE
// =========================================================================

function toTitleCase(str: string): string {
  if (!str) return '';
  return str.replace(/\w\S*/g, (txt) => txt.charAt(0).toUpperCase() + txt.substring(1).toLowerCase());
}

/**
 * Apply column mappings, formula calculations, auto-SKUs, and data cleansing to raw rows
 */
export function applyMappingAndFormulas(
  entityType: MigrationEntityType,
  rawRows: Record<string, any>[],
  mappings: Record<string, ColumnMapping>,
  formulas: FormulaConfig
): StagedRow[] {
  const fields = getFieldDefinitionsForEntity(entityType);
  const stagedRows: StagedRow[] = [];

  const existingInventory = entityType === 'inventory' ? getInventoryItems() : [];
  const existingCustomers = entityType === 'customers' ? getCustomers() : [];
  const existingSuppliers = entityType === 'suppliers' ? getSuppliers() : [];

  const existingBarcodes = new Set(existingInventory.map((i) => i.barcode).filter(Boolean));
  const existingSkus = new Set(existingInventory.map((i) => i.sku).filter(Boolean));
  const existingNames = new Set<string>();
  if (entityType === 'inventory') {
    existingInventory.forEach((it) => {
      if (it.itemName) existingNames.add(it.itemName.toLowerCase().trim());
    });
  } else if (entityType === 'customers') {
    existingCustomers.forEach((c) => {
      if (c.name) existingNames.add(c.name.toLowerCase().trim());
    });
  } else if (entityType === 'suppliers') {
    existingSuppliers.forEach((s) => {
      if (s.name) existingNames.add(s.name.toLowerCase().trim());
    });
  }

  for (let idx = 0; idx < rawRows.length; idx++) {
    const raw = rawRows[idx];
    const rowId = `stg_row_${Date.now()}_${idx}`;
    const rowData: Record<string, any> = { _rowId: rowId };
    const validationErrors: string[] = [];

    // 1. Map raw fields
    for (const field of fields) {
      const mapping = mappings[field.key];
      const sourceHeader = mapping?.sourceHeader;

      let val: any = sourceHeader ? raw[sourceHeader] : undefined;

      if (val === undefined || val === null || val === '') {
        val = field.defaultValue !== undefined ? field.defaultValue : '';
      }

      // Convert data types
      if (field.type === 'number') {
        const num = parseFloat(String(val).replace(/[^0-9.-]/g, ''));
        val = isNaN(num) ? field.defaultValue || 0 : num;
      } else if (field.type === 'string') {
        val = String(val).trim();
        if (formulas.cleanText) {
          if (field.key === 'name' || field.key === 'category') {
            val = toTitleCase(val);
          }
        }
      }

      rowData[field.key] = val;
    }

    // 2. Auto-Generate SKU / Item Code if missing or requested
    if (entityType === 'inventory') {
      const hasSku = Boolean(rowData.sku && String(rowData.sku).trim().length > 0);
      const hasItemId = Boolean(rowData.itemId && String(rowData.itemId).trim().length > 0);

      if (!hasItemId) {
        rowData.itemId = hasSku ? String(rowData.sku).trim() : `PRD_${Date.now()}_${idx}`;
      }

      if (!hasSku) {
        if (hasItemId) {
          rowData.sku = String(rowData.itemId).trim();
        } else if (formulas.autoGenerateSku) {
          const prefix = formulas.skuPrefix || 'PRD';
          const numStr = String(idx + 1).padStart(formulas.skuDigits || 4, '0');
          rowData.sku = `${prefix}-${numStr}`;
        }
      }

      // 3. Formula Engine: Case & Packaging conversion
      let cost = rowData.costPrice || 0;
      let caseQty = rowData.caseQuantity || formulas.defaultCaseQuantity || 1;
      let caseCost = rowData.caseCost || 0;

      if (formulas.caseFormula === 'case_cost_from_unit') {
        // Case Cost = Unit Cost * Case Quantity
        caseCost = Math.round(cost * caseQty * 100) / 100;
        rowData.caseCost = caseCost;
        rowData.caseQuantity = caseQty;
      } else if (formulas.caseFormula === 'unit_cost_from_case' && caseQty > 0 && caseCost > 0) {
        // Unit Cost = Case Cost / Case Quantity
        cost = Math.round((caseCost / caseQty) * 100) / 100;
        rowData.costPrice = cost;
      } else if (caseCost === 0 && cost > 0 && caseQty > 1) {
        // Default sane fallback
        rowData.caseCost = Math.round(cost * caseQty * 100) / 100;
      }

      // Stock quantity reconciliation
      const cases = Number(rowData.stockCases) || 0;
      const singles = Number(rowData.stockSingles) || 0;
      let totalUnits = Number(rowData.stockQuantity) || 0;
      if (totalUnits === 0 && (cases > 0 || singles > 0)) {
        totalUnits = cases * caseQty + singles;
        rowData.stockQuantity = totalUnits;
      } else if (totalUnits > 0 && cases === 0 && singles === 0 && caseQty > 1) {
        rowData.stockCases = Math.floor(totalUnits / caseQty);
        rowData.stockSingles = totalUnits % caseQty;
      }

      // 4. Formula Engine: Markup Pricing
      if (formulas.markupFormula === 'cost_plus_markup' && formulas.markupPercent > 0) {
        const markupMul = 1 + formulas.markupPercent / 100;
        rowData.sellingPrice = Math.round(cost * markupMul * 100) / 100;
      }

      // 5. Tax Adjustment Formula (Add VAT)
      if (formulas.taxAdjustment === 'add_vat' && formulas.taxPercent > 0) {
        const vatMul = 1 + formulas.taxPercent / 100;
        rowData.sellingPrice = Math.round(rowData.sellingPrice * vatMul * 100) / 100;
      }

      // 6. Packaging Variants (Prepacks) Processing & Parsing
      let parsedVariants: PackagingVariant[] = [];
      if (formulas.variantImportMode === 'auto_generate') {
        const currentCost = rowData.costPrice || 0;
        const currentSell = rowData.sellingPrice || 0;
        const disc = (formulas.autoVariantDiscountPercent || 5) / 100;
        if (formulas.autoVariantPreset === 'five_pack') {
          parsedVariants.push({
            id: `VAR-5PK-${idx + 1}`,
            name: 'Prepack (5s)',
            unitsPerPack: 5,
            sellPrice: Math.round(currentSell * 5 * (1 - disc) * 100) / 100,
            costPrice: Math.round(currentCost * 5 * 100) / 100,
          });
        } else if (formulas.autoVariantPreset === 'ten_pack') {
          parsedVariants.push({
            id: `VAR-10PK-${idx + 1}`,
            name: 'Pack of 10s',
            unitsPerPack: 10,
            sellPrice: Math.round(currentSell * 10 * (1 - disc) * 100) / 100,
            costPrice: Math.round(currentCost * 10 * 100) / 100,
          });
        } else if (formulas.autoVariantPreset === 'double_pack') {
          parsedVariants.push({
            id: `VAR-2PK-${idx + 1}`,
            name: 'Double Pack (2s)',
            unitsPerPack: 2,
            sellPrice: Math.round(currentSell * 2 * (1 - disc) * 100) / 100,
            costPrice: Math.round(currentCost * 2 * 100) / 100,
          });
        } else if (formulas.autoVariantPreset === 'half_pack') {
          parsedVariants.push({
            id: `VAR-HALF-${idx + 1}`,
            name: 'Half Portion (0.5)',
            unitsPerPack: 0.5,
            sellPrice: Math.round(currentSell * 0.5 * 100) / 100,
            costPrice: Math.round(currentCost * 0.5 * 100) / 100,
          });
        }
      } else if (formulas.variantImportMode !== 'none' && rowData.packagingVariants) {
        parsedVariants = parsePackagingVariantsString(rowData.packagingVariants);
      }
      rowData._parsedVariants = parsedVariants;
      if (parsedVariants.length > 0 && !rowData.packagingVariants) {
        rowData.packagingVariants = serializePackagingVariants(parsedVariants);
      }
    } else if (entityType === 'customers') {
      // Auto-generate Customer code if wanted
      if (!rowData.id) {
        const prefix = formulas.skuPrefix || 'CUST';
        const numStr = String(idx + 1).padStart(formulas.skuDigits || 4, '0');
        rowData.customerCode = `${prefix}-${numStr}`;
      }
    } else if (entityType === 'suppliers') {
      if (!rowData.id) {
        const prefix = formulas.skuPrefix || 'SUP';
        const numStr = String(idx + 1).padStart(formulas.skuDigits || 4, '0');
        rowData.supplierCode = `${prefix}-${numStr}`;
      }
    }

    // 6. Validation Checks
    for (const field of fields) {
      if (field.required) {
        const val = rowData[field.key];
        if (val === undefined || val === null || val === '') {
          validationErrors.push(`Required field '${field.label}' is missing.`);
        }
      }
    }

    // Duplicate detection
    let isDuplicate = false;
    if (entityType === 'inventory') {
      if (rowData.barcode && existingBarcodes.has(rowData.barcode)) {
        isDuplicate = true;
      } else if (rowData.sku && existingSkus.has(rowData.sku)) {
        isDuplicate = true;
      } else if (rowData.name && existingNames.has(rowData.name.toLowerCase().trim())) {
        isDuplicate = true;
      }
    } else if (rowData.name && existingNames.has(rowData.name.toLowerCase().trim())) {
      isDuplicate = true;
    }

    rowData._isValid = validationErrors.length === 0;
    rowData._validationErrors = validationErrors;
    rowData._isDuplicate = isDuplicate;

    stagedRows.push(rowData as StagedRow);
  }

  return stagedRows;
}

// =========================================================================
// COLLABORATIVE BATCH PARTITIONING ENGINE
// =========================================================================

/**
 * Split staged rows into manageable batches for staff delegation
 */
export function partitionRowsIntoBatches(
  totalRows: number,
  batchSize: number = 250,
  staffList?: Salesperson[]
): BatchPartition[] {
  const partitions: BatchPartition[] = [];
  const numBatches = Math.ceil(totalRows / batchSize);

  for (let b = 0; b < numBatches; b++) {
    const startIndex = b * batchSize;
    const endIndex = Math.min((b + 1) * batchSize - 1, totalRows - 1);
    const count = endIndex - startIndex + 1;

    // Optional round-robin assignment to active staff
    let assignedStaff: Salesperson | undefined;
    if (staffList && staffList.length > 0) {
      assignedStaff = staffList[b % staffList.length];
    }

    partitions.push({
      id: `batch_${b + 1}_${Date.now()}`,
      batchNumber: b + 1,
      title: `Batch ${b + 1} (Rows ${startIndex + 1} - ${endIndex + 1})`,
      startIndex,
      endIndex,
      totalRows: count,
      status: 'pending',
      assignedStaffId: assignedStaff?.id,
      assignedStaffName: assignedStaff?.name,
    });
  }

  return partitions;
}

// =========================================================================
// PERSISTENT JOB MANAGEMENT & LOCAL STORAGE
// =========================================================================

export function getAllMigrationJobs(): MigrationJob[] {
  if (typeof window === 'undefined' || !window.localStorage) return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_MIGRATION_JOBS_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch (err) {
    console.error('[MigrationService] Error loading migration jobs:', err);
    return [];
  }
}

export function saveMigrationJob(job: MigrationJob): void {
  if (typeof window === 'undefined' || !window.localStorage) return;
  // Prune stagedRows for committed jobs to protect localStorage 5MB quota
  const jobs = getAllMigrationJobs().filter((j) => j.id !== job.id).map((j) => {
    if (j.status === 'committed' && j.stagedRows && j.stagedRows.length > 50) {
      return { ...j, stagedRows: [] };
    }
    return j;
  });
  jobs.unshift(job);
  try {
    window.localStorage.setItem(STORAGE_MIGRATION_JOBS_KEY, JSON.stringify(jobs));
  } catch (err: any) {
    console.warn('[MigrationService] Warning saving migration job to localStorage, trimming older jobs:', err);
    try {
      // Clear older safety backup keys if quota exceeded
      for (let i = window.localStorage.length - 1; i >= 0; i--) {
        const k = window.localStorage.key(i);
        if (k && k.startsWith('saimetric_pre_migration_backup_')) {
          window.localStorage.removeItem(k);
        }
      }
      const trimmedJobs = [job];
      window.localStorage.setItem(STORAGE_MIGRATION_JOBS_KEY, JSON.stringify(trimmedJobs));
    } catch (e2) {
      console.error('[MigrationService] Failed to save migration job even after trimming:', e2);
    }
  }
}

export function getMigrationJobById(id: string): MigrationJob | null {
  const jobs = getAllMigrationJobs();
  return jobs.find((j) => j.id === id) || null;
}

export function deleteMigrationJob(id: string): void {
  if (typeof window === 'undefined' || !window.localStorage) return;
  const jobs = getAllMigrationJobs().filter((j) => j.id !== id);
  window.localStorage.setItem(STORAGE_MIGRATION_JOBS_KEY, JSON.stringify(jobs));
}

// =========================================================================
// COMMIT TO LIVE DATABASE & SAFETY ROLLBACK SNAPSHOT
// =========================================================================

export interface MigrationCommitResult {
  success: boolean;
  recordsAdded: number;
  recordsUpdated: number;
  recordsSkipped: number;
  message: string;
  rollbackKey?: string;
}

export type MigrationProgressCallback = (
  processed: number,
  total: number,
  percentage: number,
  currentItemName?: string
) => void;

/**
 * Commit validated staged rows to the live store with automated safety snapshot
 */
export function commitMigrationJob(
  job: MigrationJob,
  conflictPolicy: DuplicateConflictPolicy = 'update'
): MigrationCommitResult {
  if (typeof window === 'undefined' || !window.localStorage) {
    return { success: false, recordsAdded: 0, recordsUpdated: 0, recordsSkipped: 0, message: 'LocalStorage unavailable' };
  }

  const snapshotKey = `saimetric_pre_migration_backup_${job.id}`;

  try {
    // 1. Take safety snapshot of target table safely
    try {
      if (job.entityType === 'inventory') {
        const current = window.localStorage.getItem('saimetric_room_inventory_items') || '[]';
        window.sessionStorage.setItem(snapshotKey, current);
        window.localStorage.setItem(snapshotKey, current);
      } else if (job.entityType === 'customers') {
        const current = window.localStorage.getItem('saimetric_room_customers') || '[]';
        window.localStorage.setItem(snapshotKey, current);
      } else if (job.entityType === 'suppliers') {
        const current = window.localStorage.getItem('saimetric_room_suppliers') || '[]';
        window.localStorage.setItem(snapshotKey, current);
      }
    } catch (snapErr) {
      console.warn('[MigrationService] Snapshot storage warning (quota limited):', snapErr);
    }

    let recordsAdded = 0;
    let recordsUpdated = 0;
    let recordsSkipped = 0;

    // 2. Commit based on entity type
    const compId = getCurrentCompanyId() || 'COMP-001';
    const brId = getCurrentBranchId() || 'BR-MAIN';

    if (job.entityType === 'inventory') {
      const currentItems = getInventoryItems();
      const itemMap = new Map<string, InventoryItem>();
      currentItems.forEach((it) => {
        if (it.itemId) itemMap.set(`id_${it.itemId.toUpperCase().trim()}`, it);
        if (it.barcode) itemMap.set(`barcode_${it.barcode}`, it);
        if (it.sku) itemMap.set(`sku_${it.sku.toUpperCase().trim()}`, it);
        if (it.itemName) itemMap.set(`name_${it.itemName.toLowerCase().trim()}`, it);
      });

      for (let idx = 0; idx < job.stagedRows.length; idx++) {
        const row = job.stagedRows[idx];
        if (!row._isValid) continue;

        let existing: InventoryItem | undefined;
        if (row.itemId) existing = itemMap.get(`id_${String(row.itemId).toUpperCase().trim()}`);
        if (!existing && row.barcode) existing = itemMap.get(`barcode_${row.barcode}`);
        if (!existing && row.sku) existing = itemMap.get(`sku_${String(row.sku).toUpperCase().trim()}`);
        if (!existing && row.name) existing = itemMap.get(`name_${String(row.name).toLowerCase().trim()}`);

        const costPerUnit = Number(row.costPrice) || 0;
        const sellPriceUnit = Number(row.sellingPrice) || 0;
        const unitsPerCase = Number(row.caseQuantity) || 1;
        const costPerCase = Number(row.caseCost) || (costPerUnit * unitsPerCase);
        const sellPriceCase = sellPriceUnit * unitsPerCase;
        const totalUnits = Number(row.stockQuantity) || 0;
        const stockCases = Number(row.stockCases) || (unitsPerCase > 1 ? Math.floor(totalUnits / unitsPerCase) : 0);
        const stockSingles = Number(row.stockSingles) || (unitsPerCase > 1 ? totalUnits % unitsPerCase : totalUnits);

        const parsedVariants: PackagingVariant[] =
          Array.isArray(row._parsedVariants) && row._parsedVariants.length > 0
            ? row._parsedVariants
            : (Array.isArray(row.packagingVariants)
                ? row.packagingVariants
                : parsePackagingVariantsString(row.packagingVariants));

        // Check if this row is a prepack/variant that links to a parent product
        const parentKey = row.parentId ? String(row.parentId).trim() : null;
        if (parentKey) {
          const parentItem =
            itemMap.get(`id_${parentKey.toUpperCase()}`) ||
            itemMap.get(`sku_${parentKey.toUpperCase()}`) ||
            itemMap.get(`name_${parentKey.toLowerCase()}`);

          if (parentItem) {
            const varUnits = Number(row.variantUnits) || Number(row.caseQuantity) || 1;
            const varSell = Number(row.sellingPrice) || Number((parentItem.sellPriceUnit * varUnits).toFixed(2));
            const varCost = Number(row.costPrice) || Number((parentItem.costPerUnit * varUnits).toFixed(2));

            const curVariants: PackagingVariant[] = Array.isArray(parentItem.packagingVariants)
              ? [...parentItem.packagingVariants]
              : [];

            const existingIdx = curVariants.findIndex(
              (v) => (row.sku && v.sku === row.sku) || v.name.toLowerCase() === String(row.name).toLowerCase()
            );

            const packVar: PackagingVariant = {
              id:
                existingIdx >= 0
                  ? curVariants[existingIdx].id
                  : `VAR-${Date.now().toString().slice(-4)}-${curVariants.length + 1}`,
              name: row.name,
              unitsPerPack: varUnits,
              sellPrice: varSell,
              costPrice: varCost > 0 ? varCost : undefined,
              barcode: row.barcode || undefined,
              sku: row.sku || undefined,
            };

            if (existingIdx >= 0) {
              curVariants[existingIdx] = packVar;
            } else {
              curVariants.push(packVar);
            }

            parentItem.packagingVariants = curVariants;

            // Convert variant stock to parent units (Question 3: convert to parent units)
            const addedUnits = totalUnits > 0 ? totalUnits * varUnits : 0;
            if (addedUnits > 0) {
              parentItem.totalUnits = (parentItem.totalUnits || 0) + addedUnits;
              if (parentItem.unitsPerCase > 1) {
                parentItem.stockCases = Math.floor(parentItem.totalUnits / parentItem.unitsPerCase);
                parentItem.stockSingles = parentItem.totalUnits % parentItem.unitsPerCase;
              } else {
                parentItem.stockCases = 0;
                parentItem.stockSingles = parentItem.totalUnits;
              }
            }

            parentItem.lastUpdated = new Date().toISOString();
            saveInventoryItem(parentItem);
            if (parentItem.itemId) itemMap.set(`id_${parentItem.itemId.toUpperCase().trim()}`, parentItem);
            if (parentItem.sku) itemMap.set(`sku_${parentItem.sku.toUpperCase().trim()}`, parentItem);
            recordsUpdated++;
            continue;
          }
        }

        if (existing) {
          if (conflictPolicy === 'skip') {
            recordsSkipped++;
            continue;
          } else if (conflictPolicy === 'update') {
            const updatedItem: InventoryItem = {
              ...existing,
              itemId: row.itemId || existing.itemId,
              itemName: row.name || existing.itemName,
              costPerUnit,
              sellPriceUnit,
              unitsPerCase,
              costPerCase,
              sellPriceCase,
              totalUnits: (existing.totalUnits || 0) + totalUnits,
              stockCases: (existing.stockCases || 0) + stockCases,
              stockSingles: (existing.stockSingles || 0) + stockSingles,
              category: row.category || existing.category || 'General',
              sku: row.sku || existing.sku,
              barcode: row.barcode || existing.barcode,
              canSellAsCase: row.canSellAsCase !== undefined
                ? ['y', 'yes', 'true', '1'].includes(String(row.canSellAsCase).toLowerCase())
                : existing.canSellAsCase,
              packagingVariants: parsedVariants.length > 0 ? parsedVariants : existing.packagingVariants,
              description: row.description || existing.description,
              reorderLevelCases: Number(row.reorderLevelCases) || existing.reorderLevelCases || 2,
              reorderLevelUnits: Number(row.minStock) || existing.reorderLevelUnits || 5,
              company_id: compId,
              companyId: compId,
              branch_id: brId,
              branchId: brId,
              lastUpdated: new Date().toISOString(),
            };
            saveInventoryItem(updatedItem);
            recordsUpdated++;
            continue;
          }
        }

        // New item
        const itemId = (row.itemId && String(row.itemId).trim()) || `PRD_${Date.now()}_${idx}_${Math.random().toString(36).substring(2, 6)}`;
        const newItem: InventoryItem = {
          itemId,
          itemName: row.name,
          category: row.category || 'General',
          sku: row.sku || itemId,
          barcode: row.barcode || '',
          unitsPerCase,
          costPerCase,
          costPerUnit,
          sellPriceCase,
          sellPriceUnit,
          stockCases,
          stockSingles,
          totalUnits,
          canSellAsCase: ['y', 'yes', 'true', '1'].includes(String(row.canSellAsCase || '').toLowerCase()),
          packagingVariants: parsedVariants.length > 0 ? parsedVariants : undefined,
          description: row.description || '',
          reorderLevelCases: Number(row.reorderLevelCases) || 2,
          reorderLevelUnits: Number(row.minStock) || Math.max(5, unitsPerCase),
          company_id: compId,
          companyId: compId,
          branch_id: brId,
          branchId: brId,
          lastUpdated: new Date().toISOString(),
        };

        saveInventoryItem(newItem);
        if (newItem.itemId) itemMap.set(`id_${newItem.itemId.toUpperCase().trim()}`, newItem);
        if (newItem.sku) itemMap.set(`sku_${newItem.sku.toUpperCase().trim()}`, newItem);
        if (newItem.itemName) itemMap.set(`name_${newItem.itemName.toLowerCase().trim()}`, newItem);
        recordsAdded++;
      }
    } else if (job.entityType === 'customers') {
      const customersToImport: Customer[] = job.stagedRows
        .filter((r) => r._isValid)
        .map((row, idx) => ({
          customerId: row.customerCode || row.customerId || `CUST_${Date.now()}_${idx}`,
          name: row.name,
          phone: row.phone || '',
          address: row.address || '',
          creditLimit: Number(row.creditLimit) || 0,
          currentBalance: Number(row.currentBalance) || 0,
          company_id: compId,
          companyId: compId,
          createdBy: 'Migration_Wizard',
          createdDate: new Date().toISOString().split('T')[0],
        }));

      const res = importCustomersList(customersToImport, conflictPolicy === 'skip' ? 'merge' : 'merge');
      recordsAdded = res.added;
      recordsUpdated = res.updated;
    } else if (job.entityType === 'suppliers') {
      const suppliersToImport: Supplier[] = job.stagedRows
        .filter((r) => r._isValid)
        .map((row, idx) => ({
          supplierId: row.supplierCode || row.supplierId || `SUP_${Date.now()}_${idx}`,
          name: row.name,
          category: row.category || 'General',
          contactPerson: row.contactPerson || '',
          phone: row.phone || '',
          email: row.email || '',
          paymentTerms: row.paymentTerms || 'COD',
          address: row.address || '',
          status: 'Active' as const,
          company_id: compId,
          companyId: compId,
          createdDate: new Date().toISOString().split('T')[0],
        }));

      const res = importSuppliersList(suppliersToImport, conflictPolicy === 'skip' ? 'merge' : 'merge');
      recordsAdded = res.added;
      recordsUpdated = res.updated;
    }

    // 3. Mark job as committed
    job.status = 'committed';
    job.committedAt = new Date().toISOString();
    job.rollbackSnapshotKey = snapshotKey;
    saveMigrationJob(job);

    // Notify application listeners
    if (typeof window !== 'undefined' && typeof window.dispatchEvent === 'function') {
      window.dispatchEvent(new CustomEvent('saimetric_inventory_updated', { detail: { count: recordsAdded } }));
      window.dispatchEvent(new CustomEvent('saimetric_customers_updated', { detail: { count: recordsAdded } }));
      window.dispatchEvent(new CustomEvent('saimetric_suppliers_updated', { detail: { count: recordsAdded } }));
    }

    return {
      success: true,
      recordsAdded,
      recordsUpdated,
      recordsSkipped,
      rollbackKey: snapshotKey,
      message: `Successfully migrated ${recordsAdded + recordsUpdated} records (${recordsAdded} new, ${recordsUpdated} updated, ${recordsSkipped} skipped).`,
    };
  } catch (err: any) {
    return {
      success: false,
      recordsAdded: 0,
      recordsUpdated: 0,
      recordsSkipped: 0,
      message: `Migration commit failed: ${err.message}`,
    };
  }
}

/**
 * Asynchronous chunked commit with live progress reporting for large files
 */
export async function commitMigrationJobAsync(
  job: MigrationJob,
  conflictPolicy: DuplicateConflictPolicy = 'update',
  onProgress?: MigrationProgressCallback
): Promise<MigrationCommitResult> {
  if (typeof window === 'undefined' || !window.localStorage) {
    return { success: false, recordsAdded: 0, recordsUpdated: 0, recordsSkipped: 0, message: 'LocalStorage unavailable' };
  }

  const snapshotKey = `saimetric_pre_migration_backup_${job.id}`;

  try {
    try {
      if (job.entityType === 'inventory') {
        const current = window.localStorage.getItem('saimetric_room_inventory_items') || '[]';
        window.sessionStorage.setItem(snapshotKey, current);
        window.localStorage.setItem(snapshotKey, current);
      } else if (job.entityType === 'customers') {
        const current = window.localStorage.getItem('saimetric_room_customers') || '[]';
        window.localStorage.setItem(snapshotKey, current);
      } else if (job.entityType === 'suppliers') {
        const current = window.localStorage.getItem('saimetric_room_suppliers') || '[]';
        window.localStorage.setItem(snapshotKey, current);
      }
    } catch (snapErr) {
      console.warn('[MigrationService] Snapshot storage warning (quota limited):', snapErr);
    }

    let recordsAdded = 0;
    let recordsUpdated = 0;
    let recordsSkipped = 0;

    const compId = getCurrentCompanyId() || 'COMP-001';
    const brId = getCurrentBranchId() || 'BR-MAIN';

    if (job.entityType === 'inventory') {
      const currentItems = getInventoryItems();
      const itemMap = new Map<string, InventoryItem>();
      currentItems.forEach((it) => {
        if (it.itemId) itemMap.set(`id_${it.itemId.toUpperCase().trim()}`, it);
        if (it.barcode) itemMap.set(`barcode_${it.barcode}`, it);
        if (it.sku) itemMap.set(`sku_${it.sku.toUpperCase().trim()}`, it);
        if (it.itemName) itemMap.set(`name_${it.itemName.toLowerCase().trim()}`, it);
      });

      const totalRows = job.stagedRows.length;

      for (let idx = 0; idx < totalRows; idx++) {
        const row = job.stagedRows[idx];

        if (onProgress) {
          const percent = Math.min(99, Math.round(((idx + 1) / totalRows) * 100));
          onProgress(idx + 1, totalRows, percent, row.name || row.itemId);
          if (idx % 12 === 0) {
            await new Promise((r) => setTimeout(r, 0));
          }
        }

        if (!row._isValid) continue;

        let existing: InventoryItem | undefined;
        if (row.itemId) existing = itemMap.get(`id_${String(row.itemId).toUpperCase().trim()}`);
        if (!existing && row.barcode) existing = itemMap.get(`barcode_${row.barcode}`);
        if (!existing && row.sku) existing = itemMap.get(`sku_${String(row.sku).toUpperCase().trim()}`);
        if (!existing && row.name) existing = itemMap.get(`name_${String(row.name).toLowerCase().trim()}`);

        const costPerUnit = Number(row.costPrice) || 0;
        const sellPriceUnit = Number(row.sellingPrice) || 0;
        const unitsPerCase = Number(row.caseQuantity) || 1;
        const costPerCase = Number(row.caseCost) || (costPerUnit * unitsPerCase);
        const sellPriceCase = sellPriceUnit * unitsPerCase;
        const totalUnits = Number(row.stockQuantity) || 0;
        const stockCases = Number(row.stockCases) || (unitsPerCase > 1 ? Math.floor(totalUnits / unitsPerCase) : 0);
        const stockSingles = Number(row.stockSingles) || (unitsPerCase > 1 ? totalUnits % unitsPerCase : totalUnits);

        const parsedVariants: PackagingVariant[] =
          Array.isArray(row._parsedVariants) && row._parsedVariants.length > 0
            ? row._parsedVariants
            : (Array.isArray(row.packagingVariants)
                ? row.packagingVariants
                : parsePackagingVariantsString(row.packagingVariants));

        const parentKey = row.parentId ? String(row.parentId).trim() : null;
        if (parentKey) {
          const parentItem =
            itemMap.get(`id_${parentKey.toUpperCase()}`) ||
            itemMap.get(`sku_${parentKey.toUpperCase()}`) ||
            itemMap.get(`name_${parentKey.toLowerCase()}`);

          if (parentItem) {
            const varUnits = Number(row.variantUnits) || Number(row.caseQuantity) || 1;
            const varSell = Number(row.sellingPrice) || Number((parentItem.sellPriceUnit * varUnits).toFixed(2));
            const varCost = Number(row.costPrice) || Number((parentItem.costPerUnit * varUnits).toFixed(2));

            const curVariants: PackagingVariant[] = Array.isArray(parentItem.packagingVariants)
              ? [...parentItem.packagingVariants]
              : [];

            const existingIdx = curVariants.findIndex(
              (v) => (row.sku && v.sku === row.sku) || v.name.toLowerCase() === String(row.name).toLowerCase()
            );

            const packVar: PackagingVariant = {
              id:
                existingIdx >= 0
                  ? curVariants[existingIdx].id
                  : `VAR-${Date.now().toString().slice(-4)}-${curVariants.length + 1}`,
              name: row.name,
              unitsPerPack: varUnits,
              sellPrice: varSell,
              costPrice: varCost > 0 ? varCost : undefined,
              barcode: row.barcode || undefined,
              sku: row.sku || undefined,
            };

            if (existingIdx >= 0) {
              curVariants[existingIdx] = packVar;
            } else {
              curVariants.push(packVar);
            }

            parentItem.packagingVariants = curVariants;

            const addedUnits = totalUnits > 0 ? totalUnits * varUnits : 0;
            if (addedUnits > 0) {
              parentItem.totalUnits = (parentItem.totalUnits || 0) + addedUnits;
              if (parentItem.unitsPerCase > 1) {
                parentItem.stockCases = Math.floor(parentItem.totalUnits / parentItem.unitsPerCase);
                parentItem.stockSingles = parentItem.totalUnits % parentItem.unitsPerCase;
              } else {
                parentItem.stockCases = 0;
                parentItem.stockSingles = parentItem.totalUnits;
              }
            }

            parentItem.lastUpdated = new Date().toISOString();
            saveInventoryItem(parentItem);
            if (parentItem.itemId) itemMap.set(`id_${parentItem.itemId.toUpperCase().trim()}`, parentItem);
            if (parentItem.sku) itemMap.set(`sku_${parentItem.sku.toUpperCase().trim()}`, parentItem);
            recordsUpdated++;
            continue;
          }
        }

        if (existing) {
          if (conflictPolicy === 'skip') {
            recordsSkipped++;
            continue;
          }
          const updatedItem: InventoryItem = {
            ...existing,
            itemName: row.name || existing.itemName,
            category: row.category || existing.category,
            costPrice: costPerUnit || existing.costPrice,
            costPerUnit: costPerUnit || existing.costPerUnit,
            costPerCase: costPerCase || existing.costPerCase,
            sellingPrice: sellPriceUnit || existing.sellingPrice,
            sellPriceUnit: sellPriceUnit || existing.sellPriceUnit,
            sellPriceCase: sellPriceCase || existing.sellPriceCase,
            unitsPerCase: unitsPerCase || existing.unitsPerCase,
            stockCases: stockCases !== undefined ? stockCases : existing.stockCases,
            stockSingles: stockSingles !== undefined ? stockSingles : existing.stockSingles,
            totalUnits: totalUnits !== undefined ? totalUnits : existing.totalUnits,
            barcode: row.barcode || existing.barcode,
            sku: row.sku || existing.sku,
            packagingVariants: parsedVariants.length > 0 ? parsedVariants : existing.packagingVariants,
            lastUpdated: new Date().toISOString(),
          };
          saveInventoryItem(updatedItem);
          itemMap.set(`id_${updatedItem.itemId.toUpperCase().trim()}`, updatedItem);
          recordsUpdated++;
        } else {
          const newItemId = row.itemId
            ? String(row.itemId).trim().toUpperCase()
            : (row.sku ? String(row.sku).trim().toUpperCase() : `ITM-${Date.now().toString().slice(-5)}-${idx}`);

          const newItem: InventoryItem = {
            itemId: newItemId,
            itemName: row.name || 'Migrated Item',
            category: row.category || 'General',
            costPrice: costPerUnit,
            costPerUnit,
            costPerCase,
            sellingPrice: sellPriceUnit,
            sellPriceUnit,
            sellPriceCase,
            unitsPerCase,
            stockCases,
            stockSingles,
            totalUnits,
            reorderLevelCases: 2,
            reorderLevelUnits: 10,
            barcode: row.barcode || '',
            sku: row.sku || newItemId,
            canSellAsCase: unitsPerCase > 1,
            packagingVariants: parsedVariants,
            company_id: compId,
            branch_id: brId,
            lastUpdated: new Date().toISOString(),
          };
          saveInventoryItem(newItem);
          itemMap.set(`id_${newItem.itemId.toUpperCase().trim()}`, newItem);
          recordsAdded++;
        }
      }
    } else if (job.entityType === 'customers') {
      const customersToImport: Partial<Customer>[] = job.stagedRows
        .filter((r) => r._isValid)
        .map((r, idx) => ({
          customerId: r.customerId || `CUST-MIG-${Date.now().toString().slice(-4)}-${idx}`,
          name: r.name,
          phone: r.phone || '',
          email: r.email || '',
          companyName: r.companyName || '',
          nationalId: r.nationalId || '',
          creditLimit: Number(r.creditLimit) || 0,
          currentBalance: Number(r.openingBalance) || 0,
          status: 'Active',
          createdDate: new Date().toISOString().split('T')[0],
        }));

      const res = importCustomersList(customersToImport, conflictPolicy === 'skip' ? 'merge' : 'merge');
      recordsAdded = res.added;
      recordsUpdated = res.updated;
    } else if (job.entityType === 'suppliers') {
      const suppliersToImport: Partial<Supplier>[] = job.stagedRows
        .filter((r) => r._isValid)
        .map((r, idx) => ({
          supplierId: r.supplierId || `SUP-MIG-${Date.now().toString().slice(-4)}-${idx}`,
          name: r.name,
          contactPerson: r.contactPerson || '',
          phone: r.phone || '',
          email: r.email || '',
          address: r.address || '',
          currency: r.currency || 'USD',
          status: 'Active',
          createdDate: new Date().toISOString().split('T')[0],
        }));

      const res = importSuppliersList(suppliersToImport, conflictPolicy === 'skip' ? 'merge' : 'merge');
      recordsAdded = res.added;
      recordsUpdated = res.updated;
    }

    if (onProgress) {
      onProgress(job.stagedRows.length, job.stagedRows.length, 100, 'Complete');
    }

    job.status = 'committed';
    job.committedAt = new Date().toISOString();
    job.rollbackSnapshotKey = snapshotKey;
    saveMigrationJob(job);

    if (typeof window !== 'undefined' && typeof window.dispatchEvent === 'function') {
      window.dispatchEvent(new CustomEvent('saimetric_inventory_updated', { detail: { count: recordsAdded } }));
      window.dispatchEvent(new CustomEvent('saimetric_customers_updated', { detail: { count: recordsAdded } }));
      window.dispatchEvent(new CustomEvent('saimetric_suppliers_updated', { detail: { count: recordsAdded } }));
    }

    return {
      success: true,
      recordsAdded,
      recordsUpdated,
      recordsSkipped,
      rollbackKey: snapshotKey,
      message: `Successfully migrated ${recordsAdded + recordsUpdated} records (${recordsAdded} new, ${recordsUpdated} updated, ${recordsSkipped} skipped).`,
    };
  } catch (err: any) {
    return {
      success: false,
      recordsAdded: 0,
      recordsUpdated: 0,
      recordsSkipped: 0,
      message: `Migration commit failed: ${err.message}`,
    };
  }
}

/**
 * One-click safety rollback to the exact pre-migration snapshot
 */
export function rollbackMigrationJob(job: MigrationJob): { success: boolean; message: string } {
  if (typeof window === 'undefined' || !window.localStorage) {
    return { success: false, message: 'LocalStorage unavailable' };
  }

  const snapshotKey = job.rollbackSnapshotKey || `saimetric_pre_migration_backup_${job.id}`;
  const backupData = window.localStorage.getItem(snapshotKey);

  if (!backupData) {
    return { success: false, message: 'No pre-migration snapshot found for this job.' };
  }

  try {
    if (job.entityType === 'inventory') {
      window.localStorage.setItem('saimetric_room_inventory_items', backupData);
    } else if (job.entityType === 'customers') {
      window.localStorage.setItem('saimetric_room_customers', backupData);
    } else if (job.entityType === 'suppliers') {
      window.localStorage.setItem('saimetric_room_suppliers', backupData);
    }

    job.status = 'ready';
    job.committedAt = undefined;
    saveMigrationJob(job);

    if (typeof window !== 'undefined' && typeof window.dispatchEvent === 'function') {
      window.dispatchEvent(new CustomEvent('saimetric_inventory_updated', { detail: {} }));
      window.dispatchEvent(new CustomEvent('saimetric_customers_updated', { detail: {} }));
      window.dispatchEvent(new CustomEvent('saimetric_suppliers_updated', { detail: {} }));
    }

    return {
      success: true,
      message: `Successfully rolled back ${job.entityType} to its pre-migration snapshot.`,
    };
  } catch (err: any) {
    return {
      success: false,
      message: `Rollback failed: ${err.message}`,
    };
  }
}
