package com.saimetric.pos.reports

import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import com.saimetric.pos.reports.entities.DataDictionaryEntity
import com.saimetric.pos.reports.entities.ReportDao
import com.saimetric.pos.reports.entities.SavedReportTemplateEntity
import com.saimetric.pos.reports.entities.TableRelationshipEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

/**
 * ReportBuilderActivity: 5-Step Wizard for building any report without code.
 *
 * Steps:
 * Step 1: PICK DATA SOURCE (Dropdown of tables from data_dictionary)
 * Step 2: PICK COLUMNS (Multi-select, show display_name)
 * Step 3: JOIN DATA (Auto-suggest joins from table_relationships, toggle on/off)
 * Step 4: FILTER + GROUP + SORT (Date range, equals, >, <, GroupBy, SortBy)
 * Step 5: AGGREGATE & OUTPUT (Sum, Count, Avg, MPAndroidChart Bar/Pie Chart, CSV/PDF Export)
 */
class ReportBuilderActivity : AppCompatActivity() {

    private lateinit var reportDao: ReportDao

    // Wizard State
    private var currentStep = 1
    private val selectedTables = mutableListOf<String>("sales")
    private val selectedColumns = mutableListOf<String>()
    private val activeJoins = mutableListOf<JSONObject>()
    private val filters = mutableListOf<JSONObject>()
    private val groupByColumns = mutableListOf<String>()
    private val aggregates = mutableListOf<JSONObject>()
    private val sortByList = mutableListOf<JSONObject>()

    private var allDictionary: List<DataDictionaryEntity> = emptyList()
    private var allRelationships: List<TableRelationshipEntity> = emptyList()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // Set layout or compose view
        setupWizard()
    }

    private fun setupWizard() {
        lifecycleScope.launch {
            allDictionary = withContext(Dispatchers.IO) { reportDao.getAllDataDictionary() }
            allRelationships = withContext(Dispatchers.IO) { reportDao.getAllRelationships() }
            renderStep(1)
        }
    }

    /**
     * Render Step 1 to 5
     */
    fun renderStep(step: Int) {
        currentStep = step
        when (step) {
            1 -> {
                // Step 1: PICK DATA SOURCE
                // Displays distinct tables from data_dictionary: sales, products, inventory, customers, suppliers, staff, deliveries
                val tables = allDictionary.map { it.tableName }.distinct()
                // Bind to UI Table Picker Adapter
            }
            2 -> {
                // Step 2: PICK COLUMNS
                // Displays columns for selectedTables with display_name
                val availableCols = allDictionary.filter { selectedTables.contains(it.tableName) }
                // Bind to Multi-select Column Adapter
            }
            3 -> {
                // Step 3: JOIN DATA
                // Auto-suggest joins from table_relationships between selectedTables
                val suggested = allRelationships.filter {
                    selectedTables.contains(it.fromTable) && selectedTables.contains(it.toTable)
                }
                // Bind to Join Toggle List
            }
            4 -> {
                // Step 4: FILTER + GROUP + SORT
                // Add filter rows: Date range, equals, >, <
                // GroupBy selection from columns where is_groupable == true
                // SortBy selection (ASC / DESC)
            }
            5 -> {
                // Step 5: AGGREGATE & RUN
                // Configure Sum, Count, Avg, Min, Max
                // Execute Query via QueryBuilder.buildSafeQuery
                runCompiledReport()
            }
        }
    }

    fun nextStep() {
        if (currentStep < 5) renderStep(currentStep + 1)
    }

    fun prevStep() {
        if (currentStep > 1) renderStep(currentStep - 1)
    }

    /**
     * Executes the compiled Room @RawQuery and feeds results into Table / MPAndroidChart
     */
    private fun runCompiledReport() {
        val configJson = buildConfigJson("Custom Report", "Generated by No-Code Builder")
        val compiled = QueryBuilder.buildSafeQuery(configJson.toString())

        lifecycleScope.launch {
            try {
                val results = withContext(Dispatchers.IO) {
                    reportDao.executeRawReport(compiled.query)
                }
                // Display in TableView or MPAndroidChart (BarChart / PieChart)
                Toast.makeText(this@ReportBuilderActivity, "Report executed: ${results.size} rows", Toast.LENGTH_SHORT).show()
            } catch (e: Exception) {
                Toast.makeText(this@ReportBuilderActivity, "Error executing report: ${e.message}", Toast.LENGTH_LONG).show()
            }
        }
    }

    /**
     * Save Template into saved_report_templates table
     */
    fun saveReportTemplate(name: String, description: String) {
        val configJson = buildConfigJson(name, description)
        val templateId = "template_" + UUID.randomUUID().toString()
        val now = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US).format(Date())

        val templateEntity = SavedReportTemplateEntity(
            id = templateId,
            name = name,
            description = description,
            jsonConfig = configJson.toString(),
            createdBy = "Super Admin",
            createdAt = now
        )

        lifecycleScope.launch(Dispatchers.IO) {
            reportDao.saveTemplate(templateEntity)
            withContext(Dispatchers.Main) {
                Toast.makeText(this@ReportBuilderActivity, "Template saved successfully!", Toast.LENGTH_SHORT).show()
                // Prompt to Share Report
                val intent = Intent(this@ReportBuilderActivity, ReportPermissionsActivity::class.java).apply {
                    putExtra("REPORT_ID", templateId)
                    putExtra("REPORT_NAME", name)
                }
                startActivity(intent)
            }
        }
    }

    private fun buildConfigJson(name: String, description: String): JSONObject {
        return JSONObject().apply {
            put("name", name)
            put("description", description)
            put("tables", JSONArray(selectedTables))
            put("joins", JSONArray(activeJoins))
            put("columns", JSONArray(selectedColumns))
            if (groupByColumns.isNotEmpty()) put("group_by", JSONArray(groupByColumns))
            if (aggregates.isNotEmpty()) put("aggregates", JSONArray(aggregates))
            if (filters.isNotEmpty()) put("filters", JSONArray(filters))
            if (sortByList.isNotEmpty()) put("sort_by", JSONArray(sortByList))
            put("limit", 500)
        }
    }
}
